name: jobs examples
on:
    push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: step do job build
              run: echo Hello, world! build.
    deploy:
        runs-on: ubuntu-lates
        needs: build
        steps:
            - name: step do job2
              run: echo Hello, world! deploy
                
                
